// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ravi.learn.web.docker.Data;

namespace ravi.learn.web.docker.Migrations
{
    [DbContext(typeof(MagazineContext))]
    [Migration("20190528010257_initSqlLite")]
    partial class initSqlLite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("ravi.learn.web.docker.Models.Magazine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Magazine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MSDN MAgazine"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Docker for Dummies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "EF Core for experts"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
